# Generated by Django 5.1.5 on 2025-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
